### ISSUE TITLE
Asking Document of "dataset_untrimmed.py" for the Codes

### ISSUE THREAD

**Issue by YasmineXXX** [escorciav/moments-retrieval-page#3]
Dear Victor Escorcia,

I found that the necessary document of "dataset_untrimmed.py" is not provided in the repository. I am wondering if you could kindly share me this document. I promise they will be used only for research purposes.

Thank you very much for your kind consideration.

**Comment by escorciav** [comment]
Dear @YasmineXXX ,

Thanks for your interest in our work. My co-author (@soldelli) and I are considering releasing the code while we wait for feedback from IJCV reviewers.

While we are working on that (currently delayed due to the upcoming ICCV deadline), Could you please mention what are the details from the paper are unclear for you?

Thanks in advance for your understanding.

**Comment by YasmineXXX** [comment]
Dear @escorciav ,

While I am trying to run the "moment_freq_prior.py" and "corpus_retrieval_2nd_eval.py", I found that they all "import dataset_untrimmed". Now that "dataset_untrimmed" is not a package of Python, I suppose this is a ".py" document which you might accidentally fail to upload in the repository. As a result, I am wondering if you could kindly share me this document. 

Sorry I didn't make it clear at first. And I sincerely hope you can help me solve the puzzle. Thank you very much for your kind consideration.

**Comment by escorciav** [comment]
Sorry if I wasn't clear before.

- I just wrote an update [here](https://github.com/escorciav/moments-retrieval-page/issues/2#issuecomment-787878956)

- While we are working on the code release, we can help you giving more hints to better understand the paper, and the pseudo-code released here 😄 .

**Comment by YasmineXXX** [comment]
Dear @escorciav :

Thanks so much for your kind explanation and patience. I have already known the status of the code release. I sincerely hope that your paper will be accepted by the top-tier conference. 

Besides, I am very interested in the task of moment retrieval from video corpus. Thanks for the work you and your partner have done. Wish you good luck!

**Comment by escorciav** [comment]
OK. I guess you don't need a clarification on what the code does, and you are fine with the details in the paper. If that changes, please pass by and ask any questions here.

**Comment by YasmineXXX** [comment]
No problem! Thanks!

**Comment by tongbaochen** [comment]
Hi,  could you please release the code of dataset_untrimmed.py for research purpose? looking forward to your feedback!

**Comment by escorciav** [comment]
Thanks for your interest @tongbaochen . @soldelli a good reminder of one of the TODO (code release).
1. Did you already remove all the branches of your side projects? Lemme know when you are ready to go?
2. Sorry Mattia, I failed you on ticking the box on last year goal. Next week, inshallah.
3. I'm truly sorry @tongbaochen . As you can see, the PR from the private repo will be after ticking the box of last year. I hope you can understand us and don't hate us. If you get angry/disappointed, take a look :point_down: :point_down: :point_down: 

_Context_
This project is the most disheartening research project of my career in terms of delivering something to the community. 
- My peers and I have worked with the highest standard of research (till 2019 also high enough coding standard wrt avg research projects).
- We work on something cool. Acknowledge by pretty much all the reviewers.
- The reviewers and AC/Editors have been over rigorous with us, barely acknowledging our hard work, sweat and tears.
  - After 5 rounds of peer review and 7 revisions to our work, we still get reviews criticizing something that has been addressed.
- At least the community has backed us up, giving us >20 citations.
  - However, we are aware of some groups jealous and who have denied the recognition of our work.

**Comment by escorciav** [comment]
I was stubborn about not have released the code earlier. I was lazy for not cleaning it up. Regardless, here you go:

https://github.com/escorciav/moments-retrieval
